apply plugin: 'org.springframework.boot'

dependencies {
    // --- Módulos internos ---
    implementation project(':model')
    implementation project(':usecase')
    implementation project(':r2dbc-postgresql')
    implementation project(':reactive-web')
    implementation project(':jwt')

    // --- Librerías externas ---
    implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // --- Herramientas de desarrollo ---
    runtimeOnly 'org.springframework.boot:spring-boot-devtools'

    // --- Dependencias para pruebas ---
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}
